name: studio-nuxt-build
run-name: studio nuxt build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Force npm as the package manager (skip pnpm/yarn detection)
      - name: Set package manager to npm
        id: pkgman
        run: |
          echo "package_manager=npm" >> $GITHUB_OUTPUT
          echo "cache=npm" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.3'
          cache: npm  # Always use npm for caching

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run build
        env:
          NITRO_PRESET: github_pages
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
